<?xml version="1.0" encoding="utf-8"?>
<testsuites>
    <testsuite name="pytest" errors="0" failures="1" skipped="0" tests="3" time="33.708" timestamp="2025-05-14T17:30:52.184166+05:30" hostname="user.local">
        <testcase classname="test_example" name="test_has_title[chromium]" time="2.138" />
        <testcase classname="test_example" name="test_get_started_link[chromium]" time="0.807" />
        <testcase classname="test_example" name="test_unknown_link[chromium]" time="30.650">
            <failure message="playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.&#10;Call log:&#10;  - waiting for get_by_role(&quot;link&quot;, name=&quot;Unknow Link&quot;)">page = &lt;Page url='https://playwright.dev/'&gt;

    def test_unknown_link(page: Page):
        page.goto("https://playwright.dev/")

        # Click the get started link.
&gt;       page.get_by_role("link", name="Unknow Link").click()

test_example.py:23:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.venv/lib/python3.11/site-packages/playwright/sync_api/_generated.py:15512: in click
    self._sync(
.venv/lib/python3.11/site-packages/playwright/_impl/_locator.py:160: in click
    return await self._frame.click(self._selector, strict=True, **params)
.venv/lib/python3.11/site-packages/playwright/_impl/_frame.py:488: in click
    await self._channel.send("click", locals_to_params(locals()))
.venv/lib/python3.11/site-packages/playwright/_impl/_connection.py:61: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;playwright._impl._connection.Connection object at 0x104b45390&gt;
cb = &lt;function Channel.send.&lt;locals&gt;.&lt;lambda&gt; at 0x106a60b80&gt;, is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -&gt; Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
&gt;           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.
E           Call log:
E             - waiting for get_by_role("link", name="Unknow Link")

.venv/lib/python3.11/site-packages/playwright/_impl/_connection.py:528: TimeoutError
            </failure>
        </testcase>
    </testsuite>
</testsuites>